name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*' # version tags

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: InfoSupport.StaticCodeAnalyzer.CLI

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore Web App
      run: dotnet restore
      working-directory: InfoSupport.StaticCodeAnalyzer.WebApp

    - name: Publish Web App
      run: dotnet publish --no-restore -c Release
      working-directory: InfoSupport.StaticCodeAnalyzer.WebApp

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build -c Release

    - name: Pack
      run: dotnet pack --no-build -c Release --output nupkgs

    - name: Publish to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
